# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - master
      - main
      - prod
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "GITHUB_BASE_REF $GITHUB_BASE_REF"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "CI	$CI"
          echo "GITHUB_ACTION	$GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH	$GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY	$GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTIONS	$GITHUB_ACTIONS"
          echo "GITHUB_ACTOR	$GITHUB_ACTOR"
          echo "GITHUB_API_URL	$GITHUB_API_URL"
          echo "GITHUB_BASE_REF	$GITHUB_BASE_REF"
          echo "GITHUB_ENV	$GITHUB_ENV"
          echo "GITHUB_EVENT_NAME	$GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH	$GITHUB_EVENT_PATH"
          echo "GITHUB_GRAPHQL_URL	$GITHUB_GRAPHQL_URL"
          echo "GITHUB_HEAD_REF	$GITHUB_HEAD_REF"
          echo "GITHUB_JOB	$GITHUB_JOB"
          echo "GITHUB_PATH	$GITHUB_PATH"
          echo "GITHUB_REF	$GITHUB_REF"
          echo "GITHUB_REF_NAME	$GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED	$GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE	$GITHUB_REF_TYPE"
          echo "GITHUB_REPOSITORY	$GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER	$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_RETENTION_DAYS	$GITHUB_RETENTION_DAYS"
          echo "GITHUB_RUN_ATTEMPT	$GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID	$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER	$GITHUB_RUN_NUMBER"
          echo "GITHUB_SERVER_URL	$GITHUB_SERVER_URL"
          echo "GITHUB_SHA	$GITHUB_SHA"
          echo "GITHUB_WORKFLOW	$GITHUB_WORKFLOW"
          echo "GITHUB_WORKSPACE	$GITHUB_WORKSPACE"
          echo "RUNNER_ARCH	$RUNNER_ARCH"
          echo "RUNNER_NAME	$RUNNER_NAME"
          echo "RUNNER_OS	$RUNNER_OS"
          echo "RUNNER_TEMP	$RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE	$RUNNER_TOOL_CACHE
