# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches-ignore:
      - master
      - main
      - prod
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "export CI=$CI" | tee -a output.file
          echo "export GITHUB_ACTION=$GITHUB_ACTION" | tee -a output.file
          echo "export GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH" | tee -a output.file
          echo "export GITHUB_ACTION_REPOSITORY=$GITHUB_ACTION_REPOSITORY" | tee -a output.file
          echo "export GITHUB_ACTIONS=$GITHUB_ACTIONS" | tee -a output.file
          echo "export GITHUB_ACTOR=$GITHUB_ACTOR" | tee -a output.file
          echo "export GITHUB_API_URL=$GITHUB_API_URL" | tee -a output.file
          echo "export GITHUB_BASE_REF=$GITHUB_BASE_REF" | tee -a output.file
          echo "export GITHUB_ENV=$GITHUB_ENV" | tee -a output.file
          echo "export GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME" | tee -a output.file
          echo "export GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH" | tee -a output.file
          echo "export GITHUB_GRAPHQL_URL=$GITHUB_GRAPHQL_URL" | tee -a output.file
          echo "export GITHUB_HEAD_REF=$GITHUB_HEAD_REF" | tee -a output.file
          echo "export GITHUB_JOB=$GITHUB_JOB" | tee -a output.file
          echo "export GITHUB_PATH=$GITHUB_PATH" | tee -a output.file
          echo "export GITHUB_REF=$GITHUB_REF" | tee -a output.file
          echo "export GITHUB_REF_NAME=$GITHUB_REF_NAME" | tee -a output.file
          echo "export GITHUB_REF_PROTECTED=$GITHUB_REF_PROTECTED" | tee -a output.file
          echo "export GITHUB_REF_TYPE=$GITHUB_REF_TYPE" | tee -a output.file
          echo "export GITHUB_REPOSITORY=$GITHUB_REPOSITORY" | tee -a output.file
          echo "export GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER" | tee -a output.file
          echo "export GITHUB_RETENTION_DAYS=$GITHUB_RETENTION_DAYS" | tee -a output.file
          echo "export GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT" | tee -a output.file
          echo "export GITHUB_RUN_ID=$GITHUB_RUN_ID" | tee -a output.file
          echo "export GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" | tee -a output.file
          echo "export GITHUB_SERVER_URL=$GITHUB_SERVER_URL" | tee -a output.file
          echo "export GITHUB_SHA=$GITHUB_SHA" | tee -a output.file
          echo "export GITHUB_WORKFLOW=$GITHUB_WORKFLOW" | tee -a output.file
          echo "export GITHUB_WORKSPACE=$GITHUB_WORKSPACE" | tee -a output.file
          echo "export RUNNER_ARCH=$RUNNER_ARCH" | tee -a output.file
          echo "export RUNNER_NAME=$RUNNER_NAME" | tee -a output.file
          echo "export RUNNER_OS=$RUNNER_OS" | tee -a output.file
          echo "export RUNNER_TEMP=$RUNNER_TEMP" | tee -a output.file
          echo "export RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE" | tee -a output.file
          echo "export SUBDOMAIN=$GITHUB_REF_NAME" | sed 's#/#-#g' | tee -a output.file
          echo "************************************************"
          cat output.file

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          zip -r to-build-edu.zip . -x ./.git ./.github